# SOPS encryption
# This can be expanded to separate secrets
# by user, usergroups, host and hostgrqups
# so each can only read the secrets pertinent to it.

keys:
  - &shared age175q4v69wa6ud8kygctpazx8nxgs9r598ecdeq0rprdlkk5qt23hshjn8v3

creation_rules:
  - path_regex: secrets/shared\.yaml$
    key_groups:
      - age:
          - *shared
