{ lib, config, pkgs, ... }:

let
	picomConf = ''
# Picom configuration generated by Home Manager
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
glx-swap-method = "buffer-age";

shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.55;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;

inactive-opacity = 0.90;
active-opacity = 1.0;
blur-method = "dual_kawase";
blur-strength = 8;

no-fading-for-fullscreen = true;
detect-client-opacity = true;
detect-transient = true;
detect-rounded-corners = true;

blur-background-exclude = [ "window_type = 'dock'" "window_type = 'desktop'" "class_g = 'slop'" ];
opacity-rule = [ "90:class_g = 'Polybar'" ];
shadow-exclude = [ "class_g = 'dunst'" "class_g = 'Polybar'" "_GTK_FRAME_EXTENTS@='0,0,0,0'" ];
fade-exclude = [ "class_g = 'dunst'" "window_type = 'dock'" ];

'';
in

{
	# Install the picom package for the user
	home.packages = [ pkgs.picom ];

	# Write a standard picom config to the user's XDG config directory
	home.file.".config/picom/picom.conf" = {
		text = picomConf;
	};

	# Start picom as a systemd --user service so it's managed by Home Manager
	systemd.user.services.picom = {
		description = "Picom compositor (X11)";
		wantedBy = [ "default.target" ];
		unitConfig = {
			After = "graphical-session.target";
		};
		serviceConfig = {
			Type = "simple";
			ExecStart = "${pkgs.picom}/bin/picom --config ${config.home.homeDirectory}/.config/picom/picom.conf";
			Restart = "on-failure";
			RestartSec = 5;
		};
	};

}