apiVersion: v1
kind: Secret
metadata:
    name: pihole-web-password
    namespace: pihole
type: Opaque
stringData:
    WEBPASSWORD: ENC[AES256_GCM,data:b4X6R9dTtSo3JOYu,iv:kj6fW7zwKSWXe+K+vN5bDVfFfFNRxfyshZZ4QR6e3wo=,tag:0Fow+X0Q403lj6yfYD7ryg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Mmw3NTZoYVpUMFJ4K1B4
            ZVZ2S0pGVklUMndoNy9ON1BCcjFiWHZKTmxFCjVKRmdDWEtKeDBjSGhWSGt3c1Fm
            ZUVBOGJXRlV4SzU3dmo1YWtrYmJqS2cKLS0tIFQxSEgwcEVzVFNUWnhSNERCUXVj
            ak5VaFBsc215M0hDWlJJQzlvbWFDVFkKeo4uLa2wQCoKB1XDCnaopKNEwd6EfDDt
            1SPyws4WpwINg4JRyi328cMJ1vyy9gs9CcsQkhnWR6h1EHV2D54gnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age175q4v69wa6ud8kygctpazx8nxgs9r598ecdeq0rprdlkk5qt23hshjn8v3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T14:24:54Z"
    mac: ENC[AES256_GCM,data:n5GutSWWcPBGo7Y5U/+R6s3MstMo4Tc1gakWCMyXmoJ2/YnCqSf4Puc5OUujvMbzsdkzI7Fka97tlT6cINL/HJ9lgAB/+LtGJMxcGMXVmsKVKrvoPcKUSgpNV1O7N5HIC/NPeDz8UFUG3WOrt3sYxq6k35ScIGziTQrh0xP7roU=,iv:xOX22YaZtGNkC2+AhvokmkQFQ6xhgFLgSOcvOljJjy0=,tag:11j38qe5jARsdxtrV2cxBg==,type:str]
    version: 3.13.3
